#!/bin/bash
echo "Android Image Kitchen - UnpackImg Script";
echo "by osm0sis @ xda-developers";
echo " ";
echo "Supplied image: recovery.img";
echo " ";
echo "Removing old work folders and files . . .";
echo " ";
echo "Setting up work folders . . .";
echo " ";
echo "Image type: AOSP";
echo " ";
echo "Splitting image to "split_img/" . . .";
echo " ";
echo "ANDROID! magic found at: 0";
echo "BOARD_KERNEL_CMDLINE";
echo "BOARD_KERNEL_BASE 0x10000000";
echo "BOARD_NAME SRPOL30A000RU";
echo "BOARD_PAGE_SIZE 2048";
echo "BOARD_HASH_TYPE sha1";
echo "BOARD_KERNEL_OFFSET 0x00008000";
echo "BOARD_RAMDISK_OFFSET 0x01000000";
echo "BOARD_SECOND_OFFSET 0x00f00000";
echo "BOARD_TAGS_OFFSET 0x00000100v
echo "BOARD_DT_SIZE 460800";
echo " ";
echo "Unpacking ramdisk to "ramdisk/" . . .";
echo " ";
echo "Compression used: gzip";
echo "12436 blocks";
echo " ";
echo "Done!";
